version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-react
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    ports:
      - "8000:8000"
    networks:
      - laravel

  # mysql:
  #   image: mysql:8.0
  #   container_name: laravel-mysql
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_USER: laravel
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #   networks:
  #     - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
